id = "45673128-fd78-4bce-93e7-0d32eec0fd90"
resPack = false
author = "Cold-Mint"
versionName = "1.0"
versionNumber = 1
minGameVersion = 1

[name]
packId = "@self"
resourceType = 1
resourceKey = "dataPacksName"

[description]
packId = "@self"
resourceType = 1
resourceKey = "dataPacksDescription"
