id = "glimmerworks"
resPack = false
author = "Cold-Mint"
versionName = "1.0"
versionNumber = 1
minGameVersion = 1

[name]
packId = "@self"
resourceType = 1
resourceKey = "dataPacksName"

[description]
packId = "@self"
resourceType = 1
resourceKey = "dataPacksDescription"
