id = "glimmerworks"
resPack = false
author = "Cold-Mint"
versionName = "1.0"
versionNumber = 1
minGameVersion = 1

[name]
packId = "@self"
resourceType = "string"
resourceKey = "dataPacksName"

[description]
packId = "@self"
resourceType = "string"
resourceKey = "dataPacksDescription"

[[packDependencies]]
packId = "@core"
minVersion = 1
