[[string]]
resourceKey = "dataPacksName"
value = "GlimmerWorks"

[[string]]
resourceKey = "dataPacksDescription"
value = "The official core data pack for GlimmerWorks, providing essential game definitions and content."

[[string]]
resourceKey = "dirt"
value = "dirt"

[[string]]
resourceKey = "grass"
value = "grass"

[[string]]
resourceKey = "sand"
value = "sand"


[[string]]
resourceKey = "snow"
value = "snow"


[[string]]
resourceKey = "wooden_pickaxe"
value = "wooden pickaxe"


[[string]]
resourceKey = "simple_dig"
value = "Simple dig module"



[[string]]
resourceKey = "standard_dig"
value = "Standard dig module"


[[string]]
resourceKey = "oak_wood"
value = "oak wood"


[[string]]
resourceKey = "oak_leaf"
value = "oak leaf"


[[string]]
resourceKey = "oak"
value = "oak"


[[string]]
resourceKey = "area_marker"
value = "Precision surveying instrument"

[[string]]
resourceKey = "mining_gain_1"
value = "Mining Bonus I"


[[string]]
resourceKey = "mining_gain_2"
value = "Mining Bonus II"


[[string]]
resourceKey = "mining_gain_3"
value = "Mining Bonus III"

[[string]]
resourceKey = "mining_gain_4"
value = "Mining Bonus IV"

[[string]]
resourceKey = "mining_gain_5"
value = "Mining Bonus V"
