[[string]]
resourceKey = "dataPacksName"
value = "グリマーワークス"

[[string]]
resourceKey = "dataPacksDescription"
value = "グリマーワークス公式コアデータパックです。ゲームの基本定義とコンテンツを提供します。"

[[string]]
resourceKey = "dirt"
value = "土"

[[string]]
resourceKey = "grass"
value = "草土"


[[string]]
resourceKey = "sand"
value = "砂"


[[string]]
resourceKey = "snow"
value = "雪"


[[string]]
resourceKey = "wooden_pickaxe"
value = "木のつるはし"


[[string]]
resourceKey = "simple_dig"
value = "簡易採掘モジュール"


[[string]]
resourceKey = "standard_dig"
value = "標準採掘モジュール"


[[string]]
resourceKey = "oak_wood"
value = "オークの木板"


[[string]]
resourceKey = "oak_leaf"
value = "オークの葉"

[[string]]
resourceKey = "oak"
value = "オーク"


[[string]]
resourceKey = "area_marker"
value = "せいみつそくていき"

[[string]]
resourceKey = "mining_gain_1"
value = "採掘ブーストⅠ"

[[string]]
resourceKey = "mining_gain_2"
value = "採掘ブーストⅡ"

[[string]]
resourceKey = "mining_gain_3"
value = "採掘ブーストⅢ"

[[string]]
resourceKey = "mining_gain_4"
value = "採掘ブーストⅣ"

[[string]]
resourceKey = "mining_gain_5"
value = "採掘ブーストⅤ"

[[string]]
resourceKey = "precision_mining"
value = "せいみつさいくつ"

[[string]]
resourceKey = "fumble_chance_1"
value = "滑り手 I"

[[string]]
resourceKey = "fumble_chance_2"
value = "滑り手 II"

[[string]]
resourceKey = "fumble_chance_3"
value = "滑り手 III"