[[string]]
resourceKey = "dataPacksName"
value = "微光工坊"

[[string]]
resourceKey = "dataPacksDescription"
value = "微光工坊官方核心資料包，提供遊戲的基礎定義和內容。"

[[string]]
resourceKey = "dirt"
value = "泥土"

[[string]]
resourceKey = "grass"
value = "草地"


[[string]]
resourceKey = "sand"
value = "沙子"


[[string]]
resourceKey = "snow"
value = "雪"


[[string]]
resourceKey = "wooden_pickaxe"
value = "木鎬"


[[string]]
resourceKey = "simple_dig"
value = "簡易挖掘模組"


[[string]]
resourceKey = "standard_dig"
value = "標準挖掘模組"


[[string]]
resourceKey = "oak_wood"
value = "橡木木闆"


[[string]]
resourceKey = "oak_leaf"
value = "橡木樹葉"


[[string]]
resourceKey = "oak"
value = "橡木"


[[string]]
resourceKey = "area_marker"
value = "精準測繪儀"

[[string]]
resourceKey = "mining_gain_1"
value = "採掘增益I"

[[string]]
resourceKey = "mining_gain_2"
value = "採掘增益II"

[[string]]
resourceKey = "mining_gain_3"
value = "採掘增益III"

[[string]]
resourceKey = "mining_gain_4"
value = "採掘增益IV"

[[string]]
resourceKey = "mining_gain_5"
value = "採掘增益V"
