resourceKey = "oak"
generatorId = "tree"
#Trees must grow on the surface.
#树木必须生成在表面。
[[condition]]
processorId = "surface"
[[condition]]
processorId = "biome"
[[condition.config.definition]]
key = "biome_0"
type = "ref"
[condition.config.definition.value]
packId = "@self"
resourceType = "biome"
resourceKey = "plains"
[[condition]]
processorId = "height"
[[condition.config.definition]]
key = "maxHeightPercent"
type = "float"
value = 0.8
[[condition.config.definition]]
key = "minHeightPercent"
type = "float"
value = 0.2
[[condition]]
processorId = "hSpacing"
[[condition.config.definition]]
key = "minDistance"
type = "int"
value = 5
[[data]]
packId = "@self"
resourceType = "tile"
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = "tile"
resourceKey = "oak"
[generatorConfig]
#树叶索引
[[generatorConfig.definition]]
key = "leafDataIndex"
type = "int"
value = 0
#树干索引
[[generatorConfig.definition]]
key = "trunkDataIndex"
type = "int"
value = 1
#最大树干高度
[[generatorConfig.definition]]
key = "trunkHeightMax"
type = "int"
value = 9
#最小树干高度
[[generatorConfig.definition]]
key = "trunkHeightMin"
type = "int"
value = 3
#是否拥有树叶
[[generatorConfig.definition]]
key = "hasLeaves"
type = "bool"
value = true
#树叶半径
[[generatorConfig.definition]]
key = "leafRadius"
type = "int"
value = 3
#从顶部开始生成几团树叶？
[[generatorConfig.definition]]
key = "leafClusterCount"
type = "int"
value = 1
#每团树叶的y高度间隔
[[generatorConfig.definition]]
key = "leafVerticalSpacing"
type = "int"
value = 1
#树干宽度
[[generatorConfig.definition]]
key = "trunkWidth"
type = "int"
value = 1
