resourceKey = "start_room"
generatorId = "static"
width = 12
# 顶部 12 格木板
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
# 第5行（左右墙）
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
# 10 air
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"

# 第4行（左右墙）
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
# 10 air
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"

# 第3行（带门）
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"

# 左侧 4 air
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"

# 门洞 2 格
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"

# 右侧 4 air
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"

[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"

# 第2行（门第二层）
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"

# 左 4 air
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"

# 门
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"

# 右 4 air
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"

[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"



# 第1行（地板）
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
