resourceKey = "start_room"
generatorId = "static"
width = 12
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_wood"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@core"
resourceType = 2
resourceKey = "air"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
[[data]]
packId = "@self"
resourceType = 2
resourceKey = "oak_leaf"
