resourceKey = "mining_gain_2"
canUseAlone = false
ability = "none"

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "items/simple_dig.png"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "mining_gain_2"

[abilityConfig]
[[abilityConfig.definition]]
key = "efficiency"
type = "float"
value = 1.2
