resourceKey = "simple_dig"
canUseAlone = false
ability = "dig"

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "items/simple_dig.png"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "simple_dig"

[description]
packId = "@self"
resourceType = "string"
resourceKey = "simple_dig_description"

[abilityConfig]
[[abilityConfig.definition]]
key = "efficiency"
type = "float"
value = 0.7
