resourceKey = "simple_dig"
texture = "items/simple_dig.png"
canUseAlone = false
ability = "dig"

[name]
packId = "@self"
resourceType = 1
resourceKey = "simple_dig"

[description]
packId = "@self"
resourceType = 1
resourceKey = "simple_dig_description"

[abilityConfig]
[[abilityConfig.definition]]
key = "efficiency"
type = 1
value = 0.7
