resourceKey = "standard_dig"
canUseAlone = false
ability = "dig"

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "items/standard_dig.png"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "standard_dig"

[description]
packId = "@self"
resourceType = "string"
resourceKey = "standard_dig_description"

[abilityConfig]
[[abilityConfig.definition]]
key = "efficiency"
type = "float"
value = 1.0
