resourceKey = "standard_dig"
canUseAlone = false
ability = "dig"

[texture]
packId = "@self"
resourceType = 7
resourceKey = "items/standard_dig.png"

[name]
packId = "@self"
resourceType = 1
resourceKey = "standard_dig"

[description]
packId = "@self"
resourceType = 1
resourceKey = "standard_dig_description"

[abilityConfig]
[[abilityConfig.definition]]
key = "efficiency"
type = 1
value = 1.0
