resourceKey = "wooden_pickaxe"
slotSize = 3

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "items/pickaxe.png"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "wooden_pickaxe"
