resourceKey = "desert"
humidity = 0.2
temperature = 0.8
weirdness = 0.0
erosion = 1.0
elevation = 0.5

[[tilePlacerRefs]]
id = "fillTilePlacer"

[[tilePlacerRefs.tiles]]
packId = "@self"
resourceType = 2
resourceKey = "sand"
