resourceKey = "plains"
humidity = 0.5
temperature = 0.5
weirdness = 0.0
erosion = 1.0
elevation = 0.5
[[decorator]]
id = "fill"
[[decorator.data]]
packId = "@self"
resourceType = 2
resourceKey = "dirt"
#The surface decorator is responsible for placing grass blocks on the soil.
#表面装饰器负责在泥土上，放置草方块。
[[decorator]]
id = "surface"
[[decorator.data]]
packId = "@self"
resourceType = 2
resourceKey = "grass"
#[[decorator]]
#id = "tree"
#[[decorator.data]]
#packId = "@self"
#resourceType = 2
#resourceKey = "grass"
