resourceKey = "plateau"
humidity = 0.4
temperature = 0.3
weirdness = 0.0
erosion = 1.0
elevation = 0.7
[[decorator]]
id = "fill"
[[decorator.data]]
packId = "@self"
resourceType = "tile"
resourceKey = "snow"
