resourceKey = "dirt"
physicsType = 1
hardness = 0.6
breakable = true
layerType = 0

[texture]
packId = "@self"
resourceType = 7
resourceKey = "tiles/dirt.png"

[name]
packId = "@self"
resourceType = 1
resourceKey = "dirt"

[description]
packId = "@self"
resourceType = 1
resourceKey = "dirt_description"
