resourceKey = "dirt"
texture = "tiles/dirt.png"
physicsType = 1
hardness = 0.6
breakable = true
layerType = 0

[name]
packId = "@self"
resourceType = 1
resourceKey = "dirt"

[description]
packId = "@self"
resourceType = 1
resourceKey = "dirt_description"
