resourceKey = "grass"
physicsType = 1
hardness = 0.82
breakable = true
layerType = 0
customLootTable = true

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "tiles/grass.png"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "grass"

[description]
packId = "@self"
resourceType = "string"
resourceKey = "grass_description"

[lootTable]
packId = "@self"
resourceType = "loot"
resourceKey = "grass"
