resourceKey = "grass"
texture = "tiles/grass.png"
physicsType = 1
hardness = 0.82
breakable = true
layerType = 0

[name]
packId = "@self"
resourceType = 1
resourceKey = "grass"

[description]
packId = "@self"
resourceType = 1
resourceKey = "grass_description"
