resourceKey = "oak"
physicsType = 1
hardness = 1.5
breakable = true
layerType = 0
customLootTable = true

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "tiles/oak.png"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "oak"

[description]
packId = "@self"
resourceType = "string"
resourceKey = "oak_description"

[lootTable]
packId = "@self"
resourceType = "loot"
resourceKey = "oak"

