resourceKey = "oak"
physicsType = 1
hardness = 1.5
breakable = true
layerType = 0
customLootTable = true

[texture]
packId = "@self"
resourceType = 7
resourceKey = "tiles/oak.png"

[name]
packId = "@self"
resourceType = 1
resourceKey = "oak"

[description]
packId = "@self"
resourceType = 1
resourceKey = "oak_description"

[lootTable]
packId = "@self"
resourceType = 5
resourceKey = "oak"

