resourceKey = "oak_wood"
physicsType = 1
hardness = 0.9
breakable = true
layerType = 0

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "tiles/oak_wood.png"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "oak_wood"

[description]
packId = "@self"
resourceType = "string"
resourceKey = "oak_wood_description"
