resourceKey = "oak_leaf"
physicsType = 1
hardness = 0.2
breakable = true
layerType = 0

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "tiles/oak_leaf.png"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "oak_leaf"

[description]
packId = "@self"
resourceType = "string"
resourceKey = "oak_leaf_description"
