resourceKey = "oak_wood"
physicsType = 1
hardness = 0.9
breakable = true
layerType = 0

[texture]
packId = "@self"
resourceType = 7
resourceKey = "tiles/oak_wood.png"

[name]
packId = "@self"
resourceType = 1
resourceKey = "oak_wood"

[description]
packId = "@self"
resourceType = 1
resourceKey = "oak_wood_description"
