resourceKey = "oak_wood"
texture = "tiles/oak_wood.png"
physicsType = 1
hardness = 0.9
breakable = true
layerType = 0

[name]
packId = "@self"
resourceType = 1
resourceKey = "oak_wood"

[description]
packId = "@self"
resourceType = 1
resourceKey = "oak_wood_description"
