resourceKey = "sand"
physicsType = 1
hardness = 0.8
breakable = true
layerType = 0

[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "tiles/sand.png"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "sand"

[description]
packId = "@self"
resourceType = "string"
resourceKey = "sand_description"
