resourceKey = "sand"
physicsType = 1
hardness = 0.8
breakable = true
layerType = 0

[texture]
packId = "@self"
resourceType = 7
resourceKey = "tiles/sand.png"

[name]
packId = "@self"
resourceType = 1
resourceKey = "sand"

[description]
packId = "@self"
resourceType = 1
resourceKey = "sand_description"
