resourceKey = "snow"
physicsType = 1
hardness = 0.75
breakable = true
layerType = 0


[texture]
packId = "@self"
resourceType = "texture"
resourceKey = "tiles/snow.png"

[name]
packId = "@self"
resourceType = "string"
resourceKey = "snow"

[description]
packId = "@self"
resourceType = "string"
resourceKey = "snow_description"
