resourceKey = "snow"
texture = "tiles/snow.png"
physicsType = 1
hardness = 0.75
breakable = true
layerType = 0

[name]
packId = "@self"
resourceType = 1
resourceKey = "snow"

[description]
packId = "@self"
resourceType = 1
resourceKey = "snow_description"
