resourceKey = "snow"
physicsType = 1
hardness = 0.75
breakable = true
layerType = 0


[texture]
packId = "@self"
resourceType = 7
resourceKey = "tiles/snow.png"

[name]
packId = "@self"
resourceType = 1
resourceKey = "snow"

[description]
packId = "@self"
resourceType = 1
resourceKey = "snow_description"
